---
- name: Kill old folders
  become: true
  file: path={{ oracle_path }} state=absent

- name: Create folders
  file: path={{ oracle_path }} state=directory owner=root group=root mode=0755
  become: true

- name: Unarchive client files
  unarchive:
    src: "{{ client_path }}/{{ item }}"
    dest: "{{ oracle_path }}"
  become: true
  with_items: "{{filenames}}"
  when: dist is defined and arch is defined

- name: Link base folders
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  become: true
  with_items:
    - { src: "./{{ unzip_path }}", dest: "{{ instantclient_path }}" }
    - { src: "./instantclient/sdk/include", dest: "{{ oracle_include_path }}" }

- name: Link libraries to give versionless file
  file:
    src: "./{{ item }}.{{ libtype }}.{{ ver.link }}"
    dest: "{{ instantclient_path }}/{{ item }}.{{ libtype }}"
    state: link
  become: true
  with_items: "{{ linked_libraries }}"

- name: Define libraries in /etc/environment
  become: true
  blockinfile:
    dest: /etc/environment
    block: |
      OCI_HOME={{ instantclient_path }}
      OCI_LIB_DIR={{ instantclient_path }}
      OCI_INC_DIR={{ oracle_include_path }}
      OCI_INCLUDE_DIR={{ oracle_include_path }}
      {{ lib_path }}={{ instantclient_path }}
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - ORACLE"

- name: Save system files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  become: true
  with_items:
    - { src: ../templates/oracle.conf.j2, dest: /etc/ld.so.conf.d/oracle.conf }
    - { src: ../templates/oracle.sh.j2, dest: /etc/profile.d/oracle.sh }

- shell: ldconfig
  become: true
